### PR TITLE
Improvements, updates and bug fixes #1019, #1020

### LINKED ISSUE #1019: [bug]: "AxonOps SaaS" label in the Add Connection dialog should be "AxonOps Cloud"
### Do I have the most recent version of AxonOps Workbench installed?

- [x] I am using the most recent release

### AxonOps Workbench Version

1.0.0

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Operating System

MacOS

### Operating System Version

n/a

### Apache Cassandra Version(s)

n/a

### Bug Description

On the `AxonOps Integration` tab of the `Add Connection` dialog we let the user choose between `AxonOps SaaS` and `AxonOps Self-Host`. We use the term "AxonOps SaaS" internally but is not consistent with our public naming convention - it should be called "AxonOps Cloud" instead.

Image

### Steps to Reproduce

Open the dialog and go to the AxonOps Integration tab

### Expected Behavior

It should say "AxonOps Cloud" on the radio button's label

### Actual Behavior

it says "AxonOps SaaS"

### Severity

Low

### Further Information

_No response_

### PR DESCRIPTION
**Pull request by mhmdkrmabd**
**🛠️ Improvement/Update**
- Upgraded to **Electron v37**, including updates to `monaco-editor` and removal of outdated packages.
	- Updated drag-and-drop process to align with the Electron upgrade.
- Improved initialization and loading approaches for AxonOps dashboards.
- Removed the `chalk` package as part of dependency cleanup.
- Enhanced loading performance for connection mini-cards in the workspaces list.
- Added clearer visual feedback when a workspace path is missing during add/edit operations.
- Added new phrases to the localization files.
- Improved RTL (Right-to-Left) UI support for better experience when switching to RTL languages.

**🐛 Fix**
- #1020.
- #1019.

### CODE REVIEW

File: custom_modules/main/argv.js [hunk 1]
```diff
@@ -173,7 +173,15 @@ let init = () => {
 
   global.IsCLIMode = true
 
-  global.Chalk = require('chalk')
+  // global.Chalk = require('chalk')
```
Comment (millerjp) [inline custom_modules/main/argv.js:176]: Indicate on this comment that the code was not comprimised i.e we were not using a comprimised version, just removed it anyway

File: custom_modules/main/argv.js [hunk 2]
```diff
@@ -2,7 +2,7 @@
 const Argv = App.commandLine,
   CommandLineUsage = require('command-line-usage'),
   AppInfo = require(Path.join(__dirname, '..', '..', 'package.json')),
-  PTY = require('node-pty'),
+  PTY = require('@mhmdkrmabd/pty'),
```
Comment (millerjp) [inline custom_modules/main/argv.js:5]: We should move this under the Axonops org until pty is fixed

**Review by millerjp — CHANGES_REQUESTED** [review]
